- hosts: all
  become: yes
  tasks:
  - name: extract  file
    unarchive:
      src: https://downloads.apache.org/tomcat/tomcat-9/v9.0.50/bin/apache-tomcat-9.0.50.tar.gz
      dest: /opt/
      remote_src: yes
  - name: give permissioons
    file:
      path: /opt/apache-tomcat-9.0.50/bin/startup.sh
      mode: u+x
  - name: start tomcat
    shell: nohup /opt/apache-tomcat-9.0.50/bin/startup.sh  
